#!/bin/bash -x

found=`ls -t1 *.cc | head -n 1`

if [ -f $found ]; then
    echo 'target: $found'
else
    echo 'bad target, must exit...'
    exit
fi

fileNoExt=${found::-3}
fileWithExt=$fileNoExt'.cc'
moveTarget="${HOME}/uva/src/accepted"

tmp='tmp'
for i in {1..10}; do x=$RANDOM; tmp="${tmp}$(((x%10)+1))"; done

if [ -f $fileWithExt ]; then
    cp -n $fileWithExt $tmp
    if [ -d $moveTarget ]; then
	echo 'moving $fileWithExt to $moveTarget'
	mv $fileWithExt $moveTarget/$fileWithExt
	if [ -f $moveTarget/$fileWithExt ]; then
	    echo 'file has been moved successfully'
	    echo 'deleting temporary file: $tmp'
	    rm $tmp
	else
	    echo 'error has occurred, file not moved to $moveTarget successfully'
	    echo 'backup exists as ${tmp}, please investigate and try again'
	    exit
	fi
    fi
fi

echo '-------'
echo 'performing cleanup'

toremove=(o t sol)
for j in ${toremove[@]}
do
    if [ -f ${j} ]; then
	echo removing ${j}...
	rm ${j}
    fi
done

find -maxdepth 1 -type f -name '*~' -delete
find -maxdepth 1 -type f -name '*.in' -delete
find -maxdepth 1 -type f -name '*.out' -delete
find -maxdepth 1 -type f -name '*.ans' -delete
echo 'done cleanup...'
echo 'Success!'
