#!/bin/sh

myfile=`ls -t1 *.cc | head -n 1`
echo $myfile
g++ $myfile -std=c++11 -Wfatal-errors -o sol || exit

echo --- Answer the following questions

# Our CPP program will take two filenames as arguments
fin=input.md
fout=output.md

# Creates this file empty, or empties it if already created
> $fout
./sol $fin $fout && (diff -u $fout $fin | colordiff)

