#!/usr/bin/python

def gcd(a, b):
    return a if (b == 0) else gcd(b, a % b)

def main():
    print('-' * 10 + ' GCD(x, y) ' + '-' * 10)
    print('Enter two numbers to compute GCD, control-C to quit')
    while (1):
        a, b = map(int, input().split())
        print('GCD(%d, %d) = %d' % (a, b, gcd(a, b)))

main()
